name: Build SnipasteOCR

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install uv
      run: |
        pip install uv
        
    - name: Install dependencies
      run: |
        uv sync
        
    - name: Build Release
      run: |
        uv run pyinstaller -w main.py `
          --collect-all fastdeploy `
          --name=SnipasteOCR `
          --icon=assets/icon.ico `
          --add-data="models;models" `
          --add-data="assets;assets" `
          --add-data="config.yml;." `
          --hidden-import=pyqt6 `
          --hidden-import=PyQt6.QtWidgets `
          --hidden-import=PyQt6.QtGui `
          --hidden-import=PyQt6.QtCore `
          --hidden-import=PyQt6.sip `
          --clean `
          --noconfirm
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SnipasteOCR-release
        path: dist/SnipasteOCR

    - name: Create Zip Archive
      run: |
        Compress-Archive -Path "dist/SnipasteOCR/*" -DestinationPath "SnipasteOCR.zip"
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: SnipasteOCR.zip
        draft: false
        prerelease: false 