name: Build SnipasteOCR

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            platform: win
            asset_name: SnipasteOCR-Windows.zip
            zip_command: |
              Compress-Archive -Path "dist/SnipasteOCR/*" -DestinationPath "SnipasteOCR-Windows.zip"
              if (-not (Test-Path "SnipasteOCR-Windows.zip")) {
                  throw "Failed to create zip archive"
              }
          - os: macos-latest
            platform: mac
            asset_name: SnipasteOCR-macOS.zip
            zip_command: |
              cd dist && zip -r ../SnipasteOCR-macOS.zip SnipasteOCR
              if [ ! -f "../SnipasteOCR-macOS.zip" ]; then
                  echo "Failed to create zip archive"
                  exit 1
              fi
          - os: ubuntu-latest
            platform: linux
            asset_name: SnipasteOCR-Linux.zip
            zip_command: |
              cd dist && zip -r ../SnipasteOCR-Linux.zip SnipasteOCR
              if [ ! -f "../SnipasteOCR-Linux.zip" ]; then
                  echo "Failed to create zip archive"
                  exit 1
              fi
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache UV packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ~/AppData/Local/uv
          ~/.cache/pip
        key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-uv-
    
    - name: Install dependencies
      shell: bash
      run: |
        pip install uv
        uv sync

    - name: Build Release (Windows)
      if: matrix.platform == 'win'
      shell: pwsh
      run: |
        uv run pyinstaller -w main.py `
          --name=SnipasteOCR `
          --collect-all fastdeploy `
          --icon=assets/icon.ico `
          --add-data="models;models" `
          --add-data="assets;assets" `
          --add-data="config.yml;." `
          --hidden-import=pyqt6 `
          --hidden-import=PyQt6.QtWidgets `
          --hidden-import=PyQt6.QtGui `
          --hidden-import=PyQt6.QtCore `
          --hidden-import=PyQt6.sip `
          --clean `
          --noconfirm
        
        if (-not (Test-Path "dist/SnipasteOCR/SnipasteOCR.exe")) {
            throw "Build failed: SnipasteOCR.exe not found"
        }

    - name: Build Release (macOS/Linux)
      if: matrix.platform == 'mac' || matrix.platform == 'linux'
      shell: bash
      run: |
        uv run pyinstaller -w main.py \
          --name=SnipasteOCR \
          --collect-all fastdeploy \
          --icon=assets/icon.ico \
          --add-data="models:models" \
          --add-data="assets:assets" \
          --add-data="config.yml:." \
          --hidden-import=pyqt6 \
          --hidden-import=PyQt6.QtWidgets \
          --hidden-import=PyQt6.QtGui \
          --hidden-import=PyQt6.QtCore \
          --hidden-import=PyQt6.sip \
          --clean \
          --noconfirm
        
        if [[ "${{ matrix.platform }}" == "mac" && ! -d "dist/SnipasteOCR.app" ]]; then
          echo "Build failed: SnipasteOCR.app not found"
          exit 1
        elif [[ "${{ matrix.platform }}" == "linux" && ! -f "dist/SnipasteOCR/SnipasteOCR" ]]; then
          echo "Build failed: SnipasteOCR executable not found"
          exit 1
        fi

    - name: Create Archive
      shell: bash
      run: ${{ matrix.zip_command }}

    - name: Get Version
      id: get_version
      shell: bash
      run: |
        # 如果是tag push，使用tag名称
        if [ "${{ github.ref_type }}" = "tag" ]; then
          version="${{ github.ref_name }}"
        else
          # 否则使用分支名称-commit短hash
          branch="${{ github.ref }}"
          branch=${branch#refs/heads/}
          hash="${{ github.sha }}"
          hash=${hash:0:7}
          version="${branch}-${hash}"
        fi
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SnipasteOCR-${{ matrix.platform }}
        path: ${{ matrix.asset_name }}
        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Get Version
        id: get_version
        shell: bash
        run: |
          # 如果是tag push，使用tag名称
          if [ "${{ github.ref_type }}" = "tag" ]; then
            version="${{ github.ref_name }}"
          else
            # 否则使用分支名称-commit短hash
            branch="${{ github.ref }}"
            branch=${branch#refs/heads/}
            hash="${{ github.sha }}"
            hash=${hash:0:7}
            version="${branch}-${hash}"
          fi
          echo "version=$version" >> $GITHUB_OUTPUT
          
      - name: Delete existing release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          github_token: ${{ github.token }}
          delete_release: true
        continue-on-error: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          files: |
            SnipasteOCR-*/SnipasteOCR-*.zip
          draft: false
          prerelease: ${{ github.ref_type != 'tag' }}
          name: Release ${{ steps.get_version.outputs.version }}
          body: |
            SnipasteOCR Release ${{ steps.get_version.outputs.version }}
            
            ### 下载说明
            - Windows: 下载 SnipasteOCR-Windows.zip，解压后运行 SnipasteOCR.exe
            - macOS: 下载 SnipasteOCR-macOS.zip，解压后运行 SnipasteOCR 应用
            - Linux: 下载 SnipasteOCR-Linux.zip，解压后运行 SnipasteOCR 可执行文件
            
            ### 构建信息
            - 分支: ${{ github.ref_name }}
            - 提交: ${{ github.sha }}
            - 时间: ${{ github.event.head_commit.timestamp }}